[package]
name = "rust_first"
version = "0.1.0"
edition = "2021"
autor = "Benjamin PELLIEUX (benjaminpellieux5@gmail.com)"

[dependencies]
gtk = "0.18.1"
gio = "0.19.8"
chrono = "0.4.38"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
